server:
  port: 8080 #端口
  servlet:
    context-path: /
    session:
      timeout: 120s
spring:
  profiles:
    active: dev #开发模式
  datasource:
    url: jdbc:mysql://localhost:3306/purchaser?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    type:  # 数据源类型
    driver-class-name: com.mysql.cj.jdbc.Driver # MySql的驱动
    username: root # 数据库账号
    password: "123." # 数据库密码
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  thymeleaf:
    cache: false